/*
 * med9_stock.h - addresses of the stock MED9.1.1 functions and RAM cells that
 * patch code calls or reads.
 *
 * GENERATED by tools/gen_stock_header.py from re/symbols.csv - do not edit.
 * Regenerate with:
 *     python3 tools/gen_stock_header.py
 * `make check` in any patch runs `--check`, so a stale header fails the build.
 *
 * Addresses are CPU addresses (docs/04_re_guidelines.md section 2).  Each entry
 * carries the kind, the size and the confidence tag from the knowledge base;
 * anything below VERIFIED-STATIC must not be built on without upgrading it
 * first (docs/README.md status legend).
 *
 * The header is included from C *and* from .S files, so it contains numbers
 * and nothing else.  Signatures are not recorded here: re/symbols.csv proves
 * where a function is, not how it is called.  Spell the prototype out at the
 * call site:
 *     MED9_FN(void (*)(void), MED9_CLR_RAM_7FE889_800E18)();
 */
#ifndef MED9_STOCK_H
#define MED9_STOCK_H

/* ---- Stock functions --------------------------------------------- */
/* clr_ram_7FE889_800E18  [VERIFIED-STATIC, ghidra]  ext_flash, size 0x10
 * The leaf originally called from hook_site_100ms: li r12,0; stb r12,-0x1767(r13) (RAM 0x7FE889); */
#define MED9_CLR_RAM_7FE889_800E18 0x0011F02C

/* nop_leaf_bd9e4  [VERIFIED-STATIC, dump]  ext_flash, size 0x4
 * An EMPTY function: one instruction, blr */
#define MED9_NOP_LEAF_BD9E4        0x000BD9E4

/* can_init_mb  [VERIFIED-STATIC, ghidra]  ext_flash, size 0x78
 * can_init_mb(rx_idx) */
#define MED9_CAN_INIT_MB           0x00135750

/* can_rx_poll  [VERIFIED-STATIC, ghidra]  int_flash, size 0x4
 * can_rx_poll(rx_idx) -> DLC of a newly received frame, or 0x40 if the IFLAG bit for that buffer i */
#define MED9_CAN_RX_POLL           0x004379C8

/* nvm_block_request  [VERIFIED-STATIC, ghidra]  ext_flash, size 0x4
 * nvm(blk, off, len, mode, buf, handle) -- the EEP_CONF API */
#define MED9_NVM_BLOCK_REQUEST     0x0006131C

/* measuring_result_emit  [VERIFIED-STATIC, dump]  ext_flash, size 0x10
 * corrects the earlier cand_kwp_measblock_return at 0x038EA8 (12 bytes short) */
#define MED9_MEASURING_RESULT_EMIT 0x00038EB4

/* rksplit  [VERIFIED-STATIC, ghidra]  int_flash, size 0xEC
 * Splits rk (RAM 0x803038) over the active injections into 0x8030B4/B6 (type 0x2000), 0x8030BA/BC */
#define MED9_RKSPLIT               0x0041C3A0


/* ---- Stock RAM cells --------------------------------------------- */
/* rk_fuel_mass  [VERIFIED-STATIC, ghidra]  sram_ext, size 0x2
 * u16 relative fuel mass for the current segment, after every correction including ZGST */
#define MED9_RK                0x00803038

/* can_rx_buf_spare0  [VERIFIED-STATIC, ghidra]  sram_ext, size 0x1
 * 8 data bytes of tbl_can_rx slot 15 (id 0x7FF, TouCAN module 2 = C, message buffer 6, DLC 8) */
#define MED9_CAN_RX_BUF_SPARE0 0x00803F9C

/* nmot_w  [VERIFIED-STATIC, ghidra]  sram_int, size 0x2
 * for the use, COMMUNITY for the name */
#define MED9_NMOT_W            0x007FEE74

/* rl_w  [VERIFIED-STATIC, ghidra]  sram_int, size 0x2
 * Relative load, u16, 100%/4096 per LSB - the KFZW column-axis input (lhz -0x103e(r13) at 0x41D358 */
#define MED9_RL_W              0x007FEFB2

/* cand_mw_percyl_block  [VERIFIED-STATIC, dump]  sram_int, size 6
 * CORRECTED 2026-09-17 (E1, issue #34): the confidence was `hypothesis`, which described the NAME, */
#define MED9_DWKRZ             0x007FCE57

/* zwgru_low_octane_latch  [VERIFIED-STATIC, dump]  sram_int, size 0x1
 * The two latch bits of the stock low-octane-fuel detector zwgru_low_octane_detect 0x0F436C */
#define MED9_ZW_LOW_OCT_LATCH  0x007FD31B

/* tmst  [VERIFIED-STATIC, ghidra]  sram_ext, size 0x1
 * Engine temperature latched at start, u8, 0.75 degC per LSB with offset -48 degC */
#define MED9_TMST              0x008021F6

/* ksta_adapted  [VERIFIED-DYNAMIC, ghidra]  sram_ext, size 0x2
 * ksta * kstaa, u16, 1024 = 1.0; forced to 0x400 outside the start */
#define MED9_KSTA_ADAPTED      0x0080302C

/* zwstt  [VERIFIED-DYNAMIC, ghidra]  sram_ext, size 0x1
 * Start ignition angle, s8, 0.75 deg CA per LSB */
#define MED9_ZWSTT             0x00802096


#endif /* MED9_STOCK_H */
