#!/usr/bin/env python3
"""Generate patches/common/med9_stock.h from re/symbols.csv.

Patch code needs the addresses of a handful of stock functions and RAM cells.
Typing them into a header by hand guarantees that one day the header and the
knowledge base disagree and nobody notices, so the header is generated: the
list of *names* lives in this script, every *address* comes from
`re/symbols.csv`, and `--check` fails if the checked-in header is stale.

Only the address, the kind, the size and the confidence tag are emitted.
Prototypes are deliberately NOT invented: `re/symbols.csv` proves where a
function is, not how it is called.  A patch spells the signature out at the
call site with `MED9_FN()` from patches/common/types.h.

Usage:
    python3 tools/gen_stock_header.py                 # rewrite the header
    python3 tools/gen_stock_header.py --check         # exit 1 if it is stale
    python3 tools/gen_stock_header.py -o -            # print to stdout
"""
from __future__ import annotations

import argparse
import csv
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SYMBOLS_CSV = REPO / "re" / "symbols.csv"
HEADER = REPO / "patches" / "common" / "med9_stock.h"

# (name in re/symbols.csv, macro suffix or None to derive it from the name).
# Add a row here when a patch needs another stock address -- never a literal.
WANTED: tuple[tuple[str, str | None], ...] = (
    # functions
    ("clr_ram_7FE889_800E18", None),   # the leaf the Flash-1 hook tail-calls
    ("nop_leaf_bd9e4", None),          # the empty leaf ff_fuel's set-A hook tail-calls
    ("can_init_mb", None),
    ("can_rx_poll", None),
    ("nvm_block_request", None),
    ("measuring_result_emit", None),
    ("rksplit", None),
    # RAM
    ("rk_fuel_mass", "RK"),            # the FR calls it `rk`
    ("can_rx_buf_spare0", None),
    # RAM -- E1 (issue #34): the inputs of the ignition blend and its two
    # acceptance signals.  ff_ign.c reads all four and writes none.
    ("nmot_w", None),                  # KFZW row-axis input
    ("rl_w", None),                    # KFZW column-axis input
    ("cand_mw_percyl_block", "DWKRZ"), # the six per-cylinder knock retards
    ("zwgru_low_octane_latch", "ZW_LOW_OCT_LATCH"),
    # RAM -- E2 (issue #35): the start enrichment.  `tmst` is the column axis
    # of ff_fst_map and the gate of the start advance; the other two are the
    # cells the three E2 stubs publish, addressed absolutely in src/hooks.S and
    # read back by the group-69 handlers.
    ("tmst", None),                    # 0x8021F6, coolant latched at start
    ("ksta_adapted", None),            # 0x80302C, the cranking lever (S1)
    ("zwstt", None),                   # 0x802096, the start angle (Z1)
    ("B_stend", None),                 # 0x7FE921, the gate of both S1 stubs
)

CONFIDENCE_TAG = {
    "static": "VERIFIED-STATIC",
    "dynamic": "VERIFIED-DYNAMIC",
    "community": "COMMUNITY",
    "hypothesis": "HYPOTHESIS",
}

PREAMBLE = '''\
/*
 * med9_stock.h - addresses of the stock MED9.1.1 functions and RAM cells that
 * patch code calls or reads.
 *
 * GENERATED by tools/gen_stock_header.py from re/symbols.csv - do not edit.
 * Regenerate with:
 *     python3 tools/gen_stock_header.py
 * `make check` in any patch runs `--check`, so a stale header fails the build.
 *
 * Addresses are CPU addresses (docs/04_re_guidelines.md section 2).  Each entry
 * carries the kind, the size and the confidence tag from the knowledge base;
 * anything below VERIFIED-STATIC must not be built on without upgrading it
 * first (docs/README.md status legend).
 *
 * The header is included from C *and* from .S files, so it contains numbers
 * and nothing else.  Signatures are not recorded here: re/symbols.csv proves
 * where a function is, not how it is called.  Spell the prototype out at the
 * call site:
 *     MED9_FN(void (*)(void), MED9_CLR_RAM_7FE889_800E18)();
 */
#ifndef MED9_STOCK_H
#define MED9_STOCK_H
'''

EPILOGUE = "#endif /* MED9_STOCK_H */\n"


def load_symbols(path: Path = SYMBOLS_CSV) -> dict[str, dict]:
    with path.open(newline="") as fh:
        return {row["name"]: row for row in csv.DictReader(fh)}


def macro_name(csv_name: str, suffix: str | None) -> str:
    return "MED9_" + (suffix if suffix else csv_name.upper())


def first_sentence(text: str, limit: int = 96) -> str:
    """The first informative sentence of the notes column, for a one-line comment.

    The tag is already printed in brackets, so a leading "VERIFIED-STATIC ..."
    (with its optional "(B1, issue #11, date)" parenthesis) is dropped first --
    otherwise half the entries would say nothing but their own tag.
    """
    text = " ".join(text.split())
    for tag in CONFIDENCE_TAG.values():
        if text.startswith(tag):
            text = text[len(tag):].lstrip()
            if text.startswith("("):                 # "(B1, issue #11, 2026-09-15)"
                text = text.partition(")")[2].lstrip()
            text = text.lstrip(".:;,- ")
            break
    for sep in (". ", "; "):
        if sep in text:
            text = text.split(sep, 1)[0]
            break
    return text[:limit].rstrip() or "(see re/symbols.csv)"


def render(symbols: dict[str, dict], wanted=WANTED) -> str:
    lines = [PREAMBLE]
    missing = [n for n, _ in wanted if n not in symbols]
    if missing:
        raise SystemExit(f"re/symbols.csv has no row for: {', '.join(missing)}")

    for kind_label, kinds in (("Stock functions", ("func",)),
                              ("Stock RAM cells", ("var", "table"))):
        rows = [(n, s) for n, s in wanted if symbols[n]["kind"] in kinds]
        if not rows:
            continue
        lines.append(f"\n/* ---- {kind_label} "
                     + "-" * (60 - len(kind_label)) + " */\n")
        width = max(len(macro_name(n, s)) for n, s in rows)
        for name, suffix in rows:
            row = symbols[name]
            addr = int(row["cpu_addr"], 16)
            tag = CONFIDENCE_TAG.get(row["confidence"], row["confidence"].upper())
            size = row["size"] or "?"
            note = first_sentence(row["notes"] or row["evidence"])
            lines.append(f"/* {name}  [{tag}, {row['source']}]  "
                         f"{row['space']}, size {size}\n"
                         f" * {note} */\n")
            lines.append(f"#define {macro_name(name, suffix):<{width}} 0x{addr:08X}\n\n")

    lines.append("\n" + EPILOGUE)
    return "".join(lines)


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("-o", "--output", default=str(HEADER),
                    help="output file ('-' for stdout)")
    ap.add_argument("--symbols", default=str(SYMBOLS_CSV))
    ap.add_argument("--check", action="store_true",
                    help="do not write; exit 1 if the file on disk differs")
    a = ap.parse_args(argv)

    text = render(load_symbols(Path(a.symbols)))

    if a.output == "-":
        sys.stdout.write(text)
        return 0
    out = Path(a.output)
    if a.check:
        current = out.read_text() if out.is_file() else ""
        if current == text:
            print(f"OK: {out} is up to date with {a.symbols}")
            return 0
        print(f"FAIL: {out} is stale; run python3 tools/gen_stock_header.py",
              file=sys.stderr)
        return 1
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(text)
    print(f"wrote {out} ({len(WANTED)} symbols from {a.symbols})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
